server:
  port: 8080

spring:
  datasource:
    #url: jdbc:mysql://cpf.cn:3306/my-project?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Hongkong
    url: jdbc:mysql://127.0.0.1:3306/my-project?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Hongkong
    username: root
    password: CPF@4823
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化时建立物理连接连接的个数
    initialSize: 5
    # 最小连接池数量
    minIdle: 5
    # 最大连接池数量
    maxActive: 20
    # 获取连接时最大等待时间(ms)，即60s
    maxWait: 60000
    # 1.Destroy线程会检测连接的间隔时间；2.testWhileIdle的判断依据
    timeBetweenEvictionRunsMillis: 60000
    # 最小生存时间ms
    minEvictableIdleTimeMillis: 600000
    maxEvictableIdleTimeMillis: 900000
    # 用来检测连接是否有效的sql
    validationQuery: SELECT 1 FROM DUAL
    # 申请连接时执行validationQuery检测连接是否有效，启用会降低性能
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，启用会降低性能
    testOnReturn: false
    # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，
    # 执行validationQuery检测连接是否有效，不会降低性能
    testWhileIdle: true
    # 是否缓存preparedStatement，mysql建议关闭
    poolPreparedStatements: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
  freemarker:
    suffix: .html
    charset: utf-8
    #"关闭缓存, 即时刷新"
    cache: false
  mvc:
    # 配置静态资源映射路径，/public、/resources路径失效
    # 这个配置项是告诉springboot，应该以什么样的方式去寻找资源。默认配置为 /* 。换句话说，只有静态资源满足什么样的匹配条件，Spring Boot才会处理静态资源请求
    static-path-pattern: /static/**
  resources:
    # 用于告诉Spring Boot应该在何处查找静态资源文件, 优先级从前至后
    # 默认值 : spring.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    static-locations: classpath:/templates/,classpath:/static/

  devtools:
    restart:
      #热部署生效
      enabled: true
      additional-paths: src/main/java
      exclude: classpath:mappers/**
debug: true
logging.level.org.springframework.boot.autoconfigure: ERROR

mybatis:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mappers/base/*.xml,classpath:mappers/combine/*.xml
  # 虽然可以配置这项来进行pojo包扫描，但其实我更倾向于在mapper.xml写全类名
  type-aliases-package: cn.cpf.web.base.model.entity

# rocketMq 相关配置
rocketmq:
  useMq: true
  nameSrvAddr: 172.16.10.118:9876
  producerGroup: ItyProducerGroup
  consumerGroup: ItyConsumerGroup


# redis
redis:
  hostName: 172.16.10.113
  port: 6379
  database: 0
  password: itysit
  maxToTal: 10
  maxIdle: 5
  minIdle: 2
  maxWaitMillis: 10000
  testOnBorrow: true

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

sms:
  # 短信验证模式 => enabled: SMS服务可用, disabled(默认): SMS不可用, 如果调用接口则抛出异常, console: SMS不可用, 但会将验证码返回, 打印到控制台
  mode: console
  accessKey: XXXXXXX
  secret: XXXXXXX
  # 短信发送服务器所在区域
  regionId: XXXX
  signName: XXXX
  # 验证码有效时间,单位:秒
  expireTime: 600
  # 验证码长度
  checkCodeLength: 6

  # 邮件发送的最小时间间隔(秒)
mail.timeInterval: 60
