server:
  port: 8080

spring:
  profiles:
    # 启动 application-dal.yml 配置
    active: dal
  runner:
    openIndex: false

  freemarker:
    suffix: .html
    charset: utf-8
    #"关闭缓存, 即时刷新"
    cache: false
    settings:
      classic_compatible: true #处理空值

  mvc:
    # 配置静态资源映射路径，/public、/resources路径失效
    # 这个配置项是告诉springboot，应该以什么样的方式去寻找资源。默认配置为 /* 。换句话说，只有静态资源满足什么样的匹配条件，Spring Boot才会处理静态资源请求
    static-path-pattern: /static/**

  resources:
    # 用于告诉Spring Boot应该在何处查找静态资源文件, 优先级从前至后
    # 默认值 : spring.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    static-locations: classpath:/templates/,classpath:/static/
  aop:
    proxy-target-class: true

  devtools:
    restart:
      #热部署生效
      enabled: true
#      additional-paths: src/main/java
      exclude: classpath:mappers/**


  # redis
  redis:
    hostName: cpfree.cn
    port: 6379
    database: 6
    password: CPF@4823
    maxToTal: 10
    maxIdle: 5
    minIdle: 2
    maxWaitMillis: 10000
    testOnBorrow: true

  kafka:
    bootstrap-servers: cpfree.cn:9092
    # 该字段见 Kafka 安装包中的 consumer.proerties，可自行修改, 修改完毕后需要重启 Kafka
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000


debug: true
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.web: INFO
    org.hibernate: ERROR



# rocketMq 相关配置
rocketmq:
  useMq: true
  nameSrvAddr: 172.16.10.118:9876
  producerGroup: XXX
  consumerGroup: XXX

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

sms:
  # 短信验证模式 => enabled: SMS服务可用, disabled(默认): SMS不可用, 如果调用接口则抛出异常, console: SMS不可用, 但会将验证码返回, 打印到控制台
  mode: console
  accessKey: XXXXXXX
  secret: XXXXXXX
  # 短信发送服务器所在区域
  regionId: XXXX
  signName: XXXX
  # 验证码有效时间,单位:秒
  expireTime: 600
  # 验证码长度
  checkCodeLength: 6

  # 邮件发送的最小时间间隔(秒)
mail.timeInterval: 60
